### ISSUE TITLE
Versions compatible with Moodle 4.2, 4.3, 4.4 and future LTR 4.5

### ISSUE THREAD

**Issue by jrojas-garrido** [SN-RECIT-formation-a-distance/moodle-tool_htmlbootstrapeditor#8]
I am concerned because there are no versions that guarantee compatibility with Moodle 4.2, 4.3 and 4.4 that are already available.  Do you release the plugin only for LTR versions?  Is there any guarantee that this plugin will continue to work in Moodle 4.5 LTR ?

**Comment by gustavobazzo** [comment]
Hi @jrojas-garrido,

Thank you for your comment.
Yes, we release the plugin mainly for LTR versions.
We are working on deploying it for Moodle 4.2, 4.3, 4.4 and 4.5.
